### PR TITLE
Prevent caching

### PR DESCRIPTION
**Pull request by sbergmair**
Adding timestamp to urls on android and iOS to prevent internal caching and to get the latest version.

### CODE REVIEW

**Comment by timtraversy** [comment]
Is this documented somewhere? Both stores support this key? Or is this an http library component.

**Comment by sbergmair** [comment]
What do you mean with "both stores support this key"

**Comment by sbergmair** [comment]
It's only a url parameter that doesn't matter and does not have any effect on the result. 
The url after that should look like: <url>?<appidparameter>&timestamp=12455678
With this: the url seems to be new for the caching system and nothing gets cached

**Comment by LostInDarkMath** [comment]
@sbergmair Are you sure that this URL parameter is accepted by the APIs of the AppStore and PlayStore? Have you tested this locally?

**Comment by sbergmair** [comment]
The APIs do not need this parameter.
The idea is to blend the local caching system: 
The local caching system gets the request to `someurl.com`. The next time, the system gets the request to `someurl.com` it returns the value from the cache. To prevent this, we randomize the url with some random parameter (I used the current time millis). The api of apple and google ignore that parameter and the local caching system thinks, that this is a new url and requests the real resource.
The idea is to pass a parameter, that isn't used by the api.

**Comment by LostInDarkMath** [comment]
What exactly do you mean by "local caching system"? This plugin uses the [http](https://pub.dev/packages/http) package which does no caching as far as I know.

**Comment by sbergmair** [comment]
The caching system of the mobile phone.
Ok, what do you think, why I do not get the most recent version?

**Comment by LostInDarkMath** [comment]
I do not think that such a caching system exist. I'm using the `http` for years to make API requests and I never run into problems. 

What kind of behavior have you observed? A delay between pushing a new app version to the stores but getting the old version back in the response of the AppStore / PlayStore API? Those systems are distributed systems and it may take a while for Google and Apple to update their indices. So you simply cannot expect the correct result in real time.

**Comment by sbergmair** [comment]
Ok
That's right. 
I had this behavior: 
The app and postman did not recognize the new app. After that I reloaded postman a few times and it showed the old version (I talk about apple). Then, I added this random string and got the current version. 
Maybe a lucky moment. 
Sorry for the inconvenience. I test this in the next releases.

**Comment by LostInDarkMath** [comment]
I'm not saying that you are wrong. I just do not understand how the random string influces the result. Maybe you can do some more investigation on this? Thanks in advance :)

**Comment by pepe19000** [comment]
I run into same problem. When i create a request to Apple in postman i see a **Cache-Control: max-age:86400** header in the response that means the response is cached for a day. I think that Apple's server create this header.

I understand what @sbergmair would like to say.  If you add an extra random parameter to the query parameters you can avoid caching. 
If you don't understand how an API works feel free to look up and make sure it doesn't cause any problem if you add an extra unused parameter to the query (e.g.: itunes.apple.com/lookup?bundleId=xxx&timestamp=yyyy)

**Comment by timtraversy** [comment]
I'm somewhat torn about this. A one-day max-age is a little uncharitable, but faking new requests seems a little spammy.

**Pull request closed without merging**
