### PR TITLE
fix: added return versionStatus

### PR DESCRIPTION
**Pull request by Dansp**
added return versionStatus for work in android mobile into >>  _getAndroidStoreVersion

### CODE REVIEW

**Comment by Dansp** [comment]
I had to change my local code in flutter to work. Please update it in pub dev ;)

**Comment by Dansp** [comment]
I had to make change to work in both platforms

**Comment by timtraversy** [comment]
Thanks for the PR! I've been away from this project for a while. Does it not work to launch the Android store URL? I'd rather not depend on another project if possible.

**Comment by Dansp** [comment]
I understand for no depend from another project, but it not working in android that I've tested

**Comment by timtraversy** [comment]
What happens instead? I create the URL in this line:
https://github.com/timtraversy/new_version/blob/6bef064318f2a5a50ab7f99f7367a01dc7f493ae/lib/new_version.dart#L101
So for example, https://play.google.com/store/apps/details?id=com.google.android.youtube

**Comment by timtraversy** [comment]
Going to close this if one.

**Pull request closed without merging**
