### PR TITLE
Feature/null safety

### PR DESCRIPTION
**Pull request by GoltVik**
Hi @timtraversy 
I've migrated you awesome package to **null safety** and added **canUpdate** internal logic.
Please, check if null parameters are correct and maybe you want to add some extra logic to **canUpdate** parameter.

### CODE REVIEW

**Comment by timtraversy** [comment]
Thank you for this, I've been meaning to go to null safety. Just pushed some updates to your branch.

To properly check all versions, we might want a more complicated version comparison algorithm. But I think the following is as good as the change you started with:

```bool get canUpdate => localVersion.compareTo(storeVersion).isNegative;```

I also changed the VersionStatus class a little so that it either is returned to the user null, or with all the fields full of non-null values.

**Comment by timtraversy** [comment]
This will close #22 as well.

**Comment by GoltVik** [comment]
Perfect! This approach for **canUpdate** it's even better.

**Comment by timtraversy** [comment]
Thanks for the contribution 😄

**Pull request merged**
