### PR TITLE
Country Feature Added

### PR DESCRIPTION
**Pull request by benitogonzalezh**
~~I Change the endpoint of the appstore changing 
`https://itunes.apple.com/lookup?bundleId=$id`
to
`https://itunes.apple.com/lookup?id=$id`~~

I added a feature to choose the country for the store (Android & iOS).

### CODE REVIEW

**Comment by timtraversy** [comment]
What is the reason for the new iOS URL? When I visit https://itunes.apple.com/lookup?id=com.google.maps for example, I get the error:

```
{
 "errorMessage":"Invalid value(s) for key(s): [itunesId]",
 "queryParameters":{"output":"json", "callback":"A javascript function to handle your search results", "country":"ISO-2A country code", "limit":"The number of search results to return", "term":"A search string", "lang":"ISO-2A language code"}
}
```

**Comment by timtraversy** [comment]
Oh I see, just changing it to include the language parameter 👍

**Comment by benitogonzalezh** [comment]
> Oh I see, just changing it to include the language parameter 👍

Yes was for that, but the original also work with country code. So I restore the original and add the language feature.

**Comment by timtraversy** [comment]
Do you know if Android works in a similar way?

**Comment by timtraversy** [comment]
It looks like you can pass a `gl=US` key to the play store URL.

**Comment by benitogonzalezh** [comment]
> Do you know if Android works in a similar way?

No, i don't know... I recently research and you are right in the comment below

> It looks like you can pass a gl=US key to the play store URL.

**Comment by timtraversy** [comment]
Oh sorry before you committed that - I did some checking and I don't think it needs to be addressed. If you look up the UK version of an app only available in the US (for example: https://play.google.com/store/apps/details?id=com.Bento.Bento.prod&gl=UK), it still gives you the version number, but says `This app is not available for your device`.

Could I have the Android ID of your app to check this?

**Comment by benitogonzalezh** [comment]
@timtraversy 

I added android support to this pull request also.

**Comment by benitogonzalezh** [comment]
> Oh sorry before you committed that - I did some checking and I don't think it needs to be addressed. If you look up the UK version of an app only available in the US (for example: https://play.google.com/store/apps/details?id=com.Bento.Bento.prod&gl=UK), it still gives you the version number, but says `This app is not available for your device`.
> 
> Could I have the Android ID of your app to check this?

You are right... 
packagename: cl.ecoheroes.userapp

**Comment by timtraversy** [comment]
Yeah when I hit the API for that ID, I get `This app is not available for your device`, but I still see the version `1.5.3`

Nice app by the way 🍃 🌎

**Comment by benitogonzalezh** [comment]
Thks @timtraversy 

Finally I added compatibility for both system... In the worst case, the play store still get the version.

**Comment by yakeer** [comment]
Any estimation when a new version (double meaning :)) will be published with this fix?

**Comment by benitogonzalezh** [comment]
> Any estimation when a new version (double meaning :)) will be published with this fix?

for a whil you can use this:

  new_version:
    git:
      url: https://github.com/benitogonzalezh/new_version

**Comment by timtraversy** [comment]
Hey sorry for the delay - I'll try to get this in today. I wanted to make a few edits first.

**Pull request merged**
